import { Doctor, Patient, Admin, Appointment, MedicalRecord, WeeklySchedule } from './types';

const generateTimeSlots = (isWorking: boolean) => {
  if (!isWorking) return [];
  const slots = [];
  const times = ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30'];
  for (let i = 0; i < times.length - 1; i += 2) {
    slots.push({
      startTime: times[i],
      endTime: times[i + 1],
      isAvailable: true,
    });
  }
  return slots;
};

const defaultSchedule: WeeklySchedule = [
  { day: 'Monday', isWorking: true, slots: generateTimeSlots(true) },
  { day: 'Tuesday', isWorking: true, slots: generateTimeSlots(true) },
  { day: 'Wednesday', isWorking: true, slots: generateTimeSlots(true) },
  { day: 'Thursday', isWorking: true, slots: generateTimeSlots(true) },
  { day: 'Friday', isWorking: true, slots: generateTimeSlots(true) },
  { day: 'Saturday', isWorking: false, slots: [] },
  { day: 'Sunday', isWorking: false, slots: [] },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-1',
    email: 'dr.smith@hospital.com',
    name: 'Dr. John Smith',
    role: 'doctor',
    phone: '+1-234-567-8901',
    specialization: 'Cardiology',
    department: 'Cardiology',
    qualification: 'MD, FACC',
    experience: 15,
    bio: 'Dr. Smith is a board-certified cardiologist with over 15 years of experience in treating heart conditions.',
    consultationFee: 150,
    availability: defaultSchedule,
    createdAt: '2023-01-15',
  },
  {
    id: 'doc-2',
    email: 'dr.johnson@hospital.com',
    name: 'Dr. Emily Johnson',
    role: 'doctor',
    phone: '+1-234-567-8902',
    specialization: 'Pediatrics',
    department: 'Pediatrics',
    qualification: 'MD, FAAP',
    experience: 12,
    bio: 'Dr. Johnson specializes in pediatric care and has helped thousands of children lead healthier lives.',
    consultationFee: 120,
    availability: defaultSchedule,
    createdAt: '2023-02-20',
  },
  {
    id: 'doc-3',
    email: 'dr.williams@hospital.com',
    name: 'Dr. Michael Williams',
    role: 'doctor',
    phone: '+1-234-567-8903',
    specialization: 'Orthopedics',
    department: 'Orthopedics',
    qualification: 'MD, FAAOS',
    experience: 20,
    bio: 'Dr. Williams is an expert orthopedic surgeon specializing in sports medicine and joint replacement.',
    consultationFee: 180,
    availability: defaultSchedule,
    createdAt: '2023-03-10',
  },
  {
    id: 'doc-4',
    email: 'dr.brown@hospital.com',
    name: 'Dr. Sarah Brown',
    role: 'doctor',
    phone: '+1-234-567-8904',
    specialization: 'Dermatology',
    department: 'Dermatology',
    qualification: 'MD, FAAD',
    experience: 10,
    bio: 'Dr. Brown is a dermatologist with expertise in both medical and cosmetic dermatology.',
    consultationFee: 130,
    availability: defaultSchedule,
    createdAt: '2023-04-05',
  },
  {
    id: 'doc-5',
    email: 'dr.davis@hospital.com',
    name: 'Dr. Robert Davis',
    role: 'doctor',
    phone: '+1-234-567-8905',
    specialization: 'Neurology',
    department: 'Neurology',
    qualification: 'MD, PhD',
    experience: 18,
    bio: 'Dr. Davis is a neurologist specializing in treating complex neurological disorders.',
    consultationFee: 200,
    availability: defaultSchedule,
    createdAt: '2023-05-12',
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'pat-1',
    email: 'alice@email.com',
    name: 'Alice Cooper',
    role: 'patient',
    phone: '+1-345-678-9012',
    dateOfBirth: '1985-06-15',
    gender: 'female',
    bloodGroup: 'A+',
    address: '123 Main St, New York, NY 10001',
    emergencyContact: '+1-345-678-9013',
    createdAt: '2023-06-01',
  },
  {
    id: 'pat-2',
    email: 'bob@email.com',
    name: 'Bob Martinez',
    role: 'patient',
    phone: '+1-345-678-9014',
    dateOfBirth: '1978-03-22',
    gender: 'male',
    bloodGroup: 'O+',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    emergencyContact: '+1-345-678-9015',
    createdAt: '2023-06-10',
  },
  {
    id: 'pat-3',
    email: 'carol@email.com',
    name: 'Carol White',
    role: 'patient',
    phone: '+1-345-678-9016',
    dateOfBirth: '1990-11-08',
    gender: 'female',
    bloodGroup: 'B+',
    address: '789 Pine Rd, Chicago, IL 60601',
    emergencyContact: '+1-345-678-9017',
    createdAt: '2023-07-05',
  },
  {
    id: 'pat-4',
    email: 'david@email.com',
    name: 'David Lee',
    role: 'patient',
    phone: '+1-345-678-9018',
    dateOfBirth: '1965-09-30',
    gender: 'male',
    bloodGroup: 'AB+',
    address: '321 Elm St, Houston, TX 77001',
    emergencyContact: '+1-345-678-9019',
    createdAt: '2023-07-15',
  },
  {
    id: 'pat-5',
    email: 'emma@email.com',
    name: 'Emma Wilson',
    role: 'patient',
    phone: '+1-345-678-9020',
    dateOfBirth: '1995-01-12',
    gender: 'female',
    bloodGroup: 'O-',
    address: '654 Maple Dr, Phoenix, AZ 85001',
    emergencyContact: '+1-345-678-9021',
    createdAt: '2023-08-01',
  },
];

export const mockAdmin: Admin = {
  id: 'master-admin',
  email: 'admin@hospital.com', // password: admin
  name: 'System Administrator',
  role: 'admin',
  phone: '+1-555-000-0000',
  createdAt: '2020-01-01',
};

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    patientId: 'pat-1',
    patientName: 'Alice Cooper',
    doctorId: 'doc-1',
    doctorName: 'Dr. John Smith',
    department: 'Cardiology',
    date: '2026-03-30',
    time: '09:00',
    status: 'scheduled',
    reason: 'Regular heart checkup',
    createdAt: '2026-03-25',
  },
  {
    id: 'apt-2',
    patientId: 'pat-2',
    patientName: 'Bob Martinez',
    doctorId: 'doc-3',
    doctorName: 'Dr. Michael Williams',
    department: 'Orthopedics',
    date: '2026-03-30',
    time: '10:00',
    status: 'scheduled',
    reason: 'Knee pain consultation',
    createdAt: '2026-03-26',
  },
  {
    id: 'apt-3',
    patientId: 'pat-3',
    patientName: 'Carol White',
    doctorId: 'doc-2',
    doctorName: 'Dr. Emily Johnson',
    department: 'Pediatrics',
    date: '2026-03-29',
    time: '14:00',
    status: 'completed',
    reason: 'Child vaccination',
    notes: 'Vaccination administered successfully',
    createdAt: '2026-03-20',
  },
  {
    id: 'apt-4',
    patientId: 'pat-4',
    patientName: 'David Lee',
    doctorId: 'doc-5',
    doctorName: 'Dr. Robert Davis',
    department: 'Neurology',
    date: '2027-04-10', // future date
    time: '11:00',
    status: 'scheduled',
    reason: 'Migraine consultation',
    createdAt: '2027-04-01',
  },
  {
    id: 'apt-5',
    patientId: 'pat-5',
    patientName: 'Emma Wilson',
    doctorId: 'doc-4',
    doctorName: 'Dr. Sarah Brown',
    department: 'Dermatology',
    date: '2026-03-31',
    time: '15:00',
    status: 'scheduled',
    reason: 'Skin allergy treatment',
    createdAt: '2026-03-27',
  },
  {
    id: 'apt-6',
    patientId: 'pat-1',
    patientName: 'Alice Cooper',
    doctorId: 'doc-1',
    doctorName: 'Dr. John Smith',
    department: 'Cardiology',
    date: '2026-03-15',
    time: '09:30',
    status: 'completed',
    reason: 'Follow-up appointment',
    notes: 'Heart condition stable, continue medication',
    createdAt: '2026-03-10',
  },
  {
    id: 'apt-7',
    patientId: 'pat-2',
    patientName: 'Bob Martinez',
    doctorId: 'doc-3',
    doctorName: 'Dr. Michael Williams',
    department: 'Orthopedics',
    date: '2026-03-20',
    time: '10:30',
    status: 'cancelled',
    reason: 'Physical therapy consultation',
    createdAt: '2026-03-15',
  },
  {
    id: 'apt-8',
    patientId: 'pat-1',
    patientName: 'Alice Cooper',
    doctorId: 'doc-5',
    doctorName: 'Dr. Robert Davis',
    department: 'Neurology',
    date: '2026-04-02',
    time: '14:00',
    status: 'scheduled',
    reason: 'Headache evaluation',
    createdAt: '2026-03-28',
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'rec-1',
    appointmentId: 'apt-3',
    patientId: 'pat-3',
    patientName: 'Carol White',
    doctorId: 'doc-2',
    doctorName: 'Dr. Emily Johnson',
    visitDate: '2026-03-29',
    diagnosis: 'Routine vaccination',
    treatment: 'Administered routine vaccination per schedule and monitored the patient post-administration.',
    prescription: 'MMR Vaccine administered',
    notes: 'Child responded well to vaccination. No adverse reactions observed.',
    finalized: true,
    updatedAt: '2026-03-29',
    vitals: {
      bloodPressure: '90/60',
      temperature: '98.6 F',
      heartRate: '90 bpm',
      weight: '25 kg',
    },
  },
  {
    id: 'rec-2',
    appointmentId: 'apt-4',
    patientId: 'pat-4',
    patientName: 'David Lee',
    doctorId: 'doc-5',
    doctorName: 'Dr. Robert Davis',
    visitDate: '2026-03-28',
    diagnosis: 'Chronic Migraine',
    treatment: 'Reviewed migraine history and triggers; recommended lifestyle adjustments and preventive therapy.',
    prescription: 'Sumatriptan 50mg - Take as needed for migraine attacks\nPropranolol 40mg - Once daily for prevention',
    notes: 'Patient reports frequent migraines, approximately 3-4 times per week. Recommended lifestyle changes and stress management.',
    finalized: true,
    updatedAt: '2026-03-28',
    vitals: {
      bloodPressure: '130/85',
      temperature: '98.4 F',
      heartRate: '78 bpm',
      weight: '82 kg',
    },
  },
  {
    id: 'rec-3',
    appointmentId: 'apt-6',
    patientId: 'pat-1',
    patientName: 'Alice Cooper',
    doctorId: 'doc-1',
    doctorName: 'Dr. John Smith',
    visitDate: '2026-03-15',
    diagnosis: 'Mild Hypertension',
    treatment: 'Conducted follow-up assessment; continued current antihypertensive regimen and advised home BP monitoring.',
    prescription: 'Lisinopril 10mg - Once daily\nAspirin 81mg - Once daily',
    notes: 'Blood pressure slightly elevated. Continue current medication. Follow-up in 2 weeks.',
    finalized: true,
    updatedAt: '2026-03-15',
    vitals: {
      bloodPressure: '140/90',
      temperature: '98.6 F',
      heartRate: '72 bpm',
      weight: '65 kg',
    },
  },
];

export const departments = [
  'Cardiology',
  'Pediatrics',
  'Orthopedics',
  'Dermatology',
  'Neurology',
  'General Medicine',
  'Surgery',
  'Gynecology',
  'Ophthalmology',
  'ENT',
];
